### ISSUE TITLE
Definir 6 "bugs" de la aplicacion

### ISSUE THREAD

**Issue by Alegomcab1** [gii-is-psg2/PSG2-1920-G7-71#118]

**Comment by enrmorvaz** [comment]
Incidencias:

1. Error a la hora de añadir una mascota (Aparece el siguiente mensaje: Whitelabel Error Page)
2. A la hora de agregar un número de teléfono puedes introducir cualquier valor numérico debe de ser un valor 9 dígitos.

**Comment by ManuelAles** [comment]
Cuando hacemos una donación en negativo aparece la página de something happens. Debería mostrar que no se permiten numero negativos en el formulario.

**Comment by alefuegom** [comment]
Al pulsar el botón para editar un pet, no funciona, te da un error 500.

**Comment by ManuelAles** [comment]
Puedes añadir infinitas visitas en el mismo día a la misma mascota

**Comment by ManuelAles** [comment]
Puedes hacer visitas de pet en pasado
