### ISSUE TITLE
 Incidencia 4: reserva pet hotel

### ISSUE THREAD

**Issue by Alegomcab1** [gii-is-psg2/PSG2-1920-G7-71#130]
Puedo reservar una habitación para una mascota que ya tiene una reserva en una fecha concreta, por ejemplo puedo hacer una reserva para una mascota del 19/05/2020 al 21/05/2020 y otra del 20/05/2020 al 21/05/2020

**Comment by ManuelAles** [comment]
pull request a develop, falta master
