### ISSUE TITLE
Definir 6 request que aniada valor a la aplicacion

### ISSUE THREAD

**Issue by Alegomcab1** [gii-is-psg2/PSG2-1920-G7-71#94]
- [ ] Alejandro G
- [x] Alejandro F
- [x] Manuel
- [x] Enrique R
- [x] Enrique M
- [x] Rafael

**Comment by alefuegom** [comment]
Podríamos mejorar la aplicación, permitiendo al dueño de una mascota ver el historial de RoomBooks que tiene su mascota

**Comment by rafliefue** [comment]
Idea: Implementar paseos, un owner podrá elegir una de sus mascotas y crear una entreada de paseo(fecha), donde pondrá el tiempo estimado y la intensidad del paseo(Alta, media, baja).

**Comment by enrmorvaz** [comment]
Idea: Establecer un filtro de búsqueda donde muestre únicamente aquellas causas que se encuentran abiertas.
Idea: Establecer un botón en la pagina de causas que te dirija a un historial de causas, para que el usuario pueda ver todas las causas que la clínica ha realizado.

**Comment by enrmorvaz** [comment]
Idea: Establecer un filtro de búsqueda donde muestre únicamente aquellas causas que se encuentran abiertas.
Idea: Establecer un botón en la pagina de causas que te dirija a un historial de causas, para que el usuario pueda ver todas las causas que la clínica ha realizado.

**Comment by enrmorvaz** [comment]
Idea: Establecer un filtro de búsqueda donde muestre únicamente aquellas causas que se encuentran abiertas para que el usuario pueda donar en aquellas causas de formas mas rápida y sencilla.
Idea: Establecer un botón en la pagina de causas que te dirija a un historial de causas, para que el usuario pueda ver todas las causas que la clínica ha realizado.

**Comment by enrreigut** [comment]
Aparición de un mensaje que te notifique cuando una mascota ha sido borrada

**Comment by ManuelAles** [comment]
Quitar el logo de la universidad de sevilla con el fondo blando por otro que que se adapte mejor a los colores de la pagina.
